Repository Shourya1311/HacktoberFest-Pr-Merge, pull requests merged in 2022-10, with the labels that each got.

#5 Added .gitignore file , about Stack and its implementation using Array and Linked List
  .gitignore
  STACK/01Intro_to_Stack.c
  STACK/02StackUsingArray.c
  STACK/03StackUsingLinkedList.c
Labels: hacktoberfest-accepted

#6 link list
  link_list.c
Labels: hacktoberfest-accepted

#7 brightness
  Brightness/main.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#9 C PROGRAM TO FIND AREA
  area.c
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#10 Create Subset_sum_equal_k.cpp
  DP_question/Subset_sum_equal_k.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#12 Create agecal
  agecal
Labels: good first issue, hacktoberfest-accepted
